### ISSUE TITLE
LLaMa-2 7B model weights missing

### ISSUE THREAD

**Issue by gsoykan** [KUIS-AI/kuacc-llm#1]
The LLaMa-2 7B model weights are not available at the expected path /datasets/NLP/huggingface/hub/models--meta-llama--Llama-2-7b. Instead, the folder location only contains a reference file (ref). The original weights are available at https://huggingface.co/meta-llama/Llama-2-7b.

Request:

Please add the LLaMa-2 7B model weights to the expected path /datasets/NLP/huggingface/hub/models--meta-llama--Llama-2-7b. This will make it easier for users to access and use the model.
Thank you!

**Comment by denizyuret** [comment]
The huggingface transformers compatible version is available as
"meta-llama/Llama-2-7b-hf".
